[phases.setup]
nixPkgs = ['python311', 'gcc', 'pkg-config', 'mysql80']

[phases.install]
cmds = ['pip install -r requirements/prod.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 4'