[phases.setup]
nixPkgs = ['python311', 'gcc', 'pkg-config', 'mysql-client', 'libmysqlclient-dev']

[phases.install]
cmds = ['pip install -r requirements/prod.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn config.wsgi --bind 0.0.0.0:$PORT'